services:
  chronicler-web:
    build:
      context: src/chronicler-react
      dockerfile: Dockerfile
    ports:
      - "5161:5161"
    depends_on:
      - chronicler-api
    restart: always

  chronicler-api:
    build:
      context: .
      dockerfile: src/Chronicler.Api/Dockerfile
    environment:
      - JWT_KEY=${JWT_KEY}
      - CHRONICLER_DB_PATH=/data/chronicler.db
    ports:
      - "5160:5160"
    volumes:
      - /mnt/media/4tb-media/AudioBooks:/app/Library        # audiobook files
      - ./updates:/app/updates        # APK builds for OTA updates
      - ./logs:/app/logs              # application logs
      - chronicler-data:/data         # SQLite database
    restart: always

volumes:
  chronicler-data:
