services:
  chronicler-web:
    build:
      context: .
      dockerfile: src/Chronicler.Web/Dockerfile
    environment:
      - CHRONICLER_API_URL=http://192.168.1.71:5160
      - Urls=http://+:5161
    ports:
      - "5161:5161"
    restart: always

  chronicler-api:
    build:
      context: .
      dockerfile: src/Chronicler.Api/Dockerfile
    environment:
      - JWT_KEY=${JWT_KEY}
      - CHRONICLER_DB_PATH=/data/chronicler.db
    ports:
      - "5160:5160"
    volumes:
      - ./Library:/app/Library        # audiobook files
      - ./updates:/app/updates        # APK builds for OTA updates
      - ./logs:/app/logs              # application logs
      - chronicler-data:/data         # SQLite database
    restart: always

volumes:
  chronicler-data:
